name: workflow01
on: [push,workflow_dispatch]
jobs:  
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: This is greetings Step
        run: echo "This is greeting statement"
      - name: This is Exit step
        run: echo "This is Exit"
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: This second job
        run: echo " this is starting of 2.1"
      